dataset:
  train:
    transaction: "Data/Train/SAV_TXN_Data.csv"
    accountInfo: "Data/Train/ACCTS_Data.csv"
    idInfo: "Data/Train/ID_Data.csv"
    watchList: "Data/Train/ECCUS_Data.csv"
  test:
    transaction: "Data/Test/SAV_TXN_Data.csv"
    accountInfo: "Data/Test/ACCTS_Data.csv"
    idInfo: "Data/Test/ID_Data.csv"
    watchList: "output.csv"
  numericalCols: [
      # ACCTS_Data
      'ACCT_OPEN_DT_MAIN', 
      'ACCT_OPEN_DT_OWN', 
      # ID_Data
      'AUM_AMT_MAIN', 'DATE_OF_BIRTH_MAIN', 
      'AUM_AMT_OWN', 'DATE_OF_BIRTH_OWN', 
      # SAV_TXN_Data
      'TX_DATE', 'TX_TIME', 'TX_AMT', 'PB_BAL', 'mb_check', 'eb_check'
    ]
  categoricalCols: [
      # ACCTS_Data
      'CANCEL_NO_CONTACT_MAIN', 'IS_DIGITAL_MAIN',
      'CANCEL_NO_CONTACT_OWN', 'IS_DIGITAL_OWN',
      # ID_Data
      'CNTY_CD_MAIN',
      'CNTY_CD_OWN',
      # SAV_TXN_Data
      'DRCR', 'CHANNEL_CODE', 'TRN_CODE', 'BRANCH_NO', 'EMP_NO', 'SAME_NUMBER_IP', 'SAME_NUMBER_UUID', 'DAY_OF_WEEK' 
    ]
  categoryEmbedding: "./Data/CategoryEmbedding.yaml"
  validateSplit: 0.1
  
parameter:
  batchSize: 128
  learningRate: 0.0001
  attention_head: 4
  num_layers: 8
  d_model: 128
  epochs: 30

model:
  textEmbeddingModel: "paraphrase-multilingual-MiniLM-L12-v2"